### ISSUE TITLE
Non-fatal POSTIN scriptlet failure in rpm package hplip-3.19.8-1.oc00.i686

### ISSUE THREAD

**Issue by LewisR** [bitwiseworks/hplip-os2#2]
Fresh install of ArcaOS trunk (new r95) with hplip-3.17.11-1.oc00.i686. During update, I received:

`Non-fatal POSTIN scriptlet failure in rpm package hplip-3.19.8-1.oc00.i686
warning: group lp does not exist - using root
/@unixroot/var/tmp/rpm-tmp.SmotnB: 4: /@unixroot/var/tmp/rpm-tmp.SmotnB: %ldconf
ig_scriptlets: not found
warning: %post(hplip-3.19.8-1.oc00.i686) scriptlet failed, exit status 127`

**Comment by SilvanScherrer** [comment]
if you have the latest klusrmgr this should not happen. please see if thats the case. as klusrmgr adds the group lp among a lot others.

**Comment by SilvanScherrer** [comment]
the ldconfig_scriplets issue is locally fixed since long :) but not released so far, as I'm not done with sane-backend testing. I will let the issue open until next hplip is released.

**Comment by LewisR** [comment]
Latest klusrmgr is in the bootstrap, and the groups file includes the lp group. There may be some corruption in the groups file; I'll have to look at that. I also notice an issue with the User home directory as distributed in the bootstrap, which points to the home directory on my build system. That's a separate issue for me to fix.

Meanwhile, I'll wait for the next hplip before updating this in the ArcaOS on-disc repo.

Thanks, Silvan.

**Comment by LewisR** [comment]
I think I see the group problem. Correcting that, now. the User home directory issue is another matter, but likewise unrelated to this ticket.

**Comment by SilvanScherrer** [comment]
new hplip in rel might take a longer while. as I first need to test sane-backend as said. And for that I need testers. I will upload a build soon to exp.

**Comment by SilvanScherrer** [comment]
fixed in latest rpm
